-- ==============================================================================
-- 秦安县秦剧团云端预约系统 · PostgreSQL 13+ 初始化脚本 v1.0
-- 文档来源：F-1 §二（PG 13+ 备选栈 / E-5）
-- 类型映射（MySQL → PostgreSQL）：
--   DATETIME           → TIMESTAMP(0)
--   TINYINT(1)         → BOOLEAN
--   INT                → INTEGER
--   BIGINT UNSIGNED    → BIGINT GENERATED BY DEFAULT AS IDENTITY
--   DECIMAL(M,D)       → NUMERIC(M,D)
--   JSON               → JSONB（PG 推荐二进制JSON · 支持 GIN 索引）
--   MEDIUMTEXT/LONGTEXT→ TEXT
--   VARCHAR(N) COLLATE utf8mb4_0900_ai_ci → VARCHAR(N) COLLATE "zh_CN.utf8"
--   ON UPDATE CURRENT_TIMESTAMP → 触发器 trig_set_updated_at()
--   AUTO_INCREMENT     → GENERATED BY DEFAULT AS IDENTITY
--   CREATE INDEX IF NOT EXISTS → PG 9.5+ 原生支持
--   INSERT ... ON DUPLICATE KEY UPDATE → INSERT ... ON CONFLICT (pk) DO UPDATE SET
--   FOREIGN_KEY_CHECKS=0 → START TRANSACTION / SET CONSTRAINTS ALL DEFERRED
-- ==============================================================================
SET client_encoding = 'UTF8';
SET standard_conforming_strings = on;
SET check_function_bodies = false;
SET client_min_messages = warning;
SET default_table_access_method = heap;
SET timezone = 'Asia/Shanghai';

-- 启用 pgcrypto (UUID / 哈希函数，bcrypt需要 pgcrypto 扩展)
CREATE EXTENSION IF NOT EXISTS pgcrypto;
CREATE EXTENSION IF NOT EXISTS pg_trgm;      -- 中文模糊搜索（姓名/电话 LIKE %xxx%）
CREATE EXTENSION IF NOT EXISTS btree_gin;   -- JSONB 字段支持

-- ------------------------------------------------------------------------------
-- 前置：3 层账号隔离（F-1 §2.0 / M-2 P0，PG 使用 ROLE 权限体系）
--   $DB_USER     → qaxqjt_app        CONNECT + SELECT/INSERT/UPDATE/DELETE
--   $DB_MIG_USER → qaxqjt_migrate    SUPERUSER 级（本机/容器使用）
--   $DB_READ     → qaxqjt_read       CONNECT + SELECT
-- 注：CREATE ROLE IF NOT EXISTS 需要 PG 14+，若 PG13 用 DO $$ 容错
-- ------------------------------------------------------------------------------
DO $$
BEGIN
  IF NOT EXISTS (SELECT 1 FROM pg_roles WHERE rolname='qaxqjt_app') THEN
    CREATE ROLE qaxqjt_app LOGIN PASSWORD '__APP_PASSWORD_FROM_ENV__';
  END IF;
  IF NOT EXISTS (SELECT 1 FROM pg_roles WHERE rolname='qaxqjt_migrate') THEN
    CREATE ROLE qaxqjt_migrate LOGIN PASSWORD '__MIGRATE_PASSWORD_FROM_ENV__' SUPERUSER;
  END IF;
  IF NOT EXISTS (SELECT 1 FROM pg_roles WHERE rolname='qaxqjt_read') THEN
    CREATE ROLE qaxqjt_read LOGIN PASSWORD '__READ_PASSWORD_FROM_ENV__';
  END IF;
END$$;

GRANT CONNECT ON DATABASE qaxqjt_prod TO qaxqjt_app, qaxqjt_read;
GRANT USAGE ON SCHEMA public TO qaxqjt_app, qaxqjt_read;

-- ------------------------------------------------------------------------------
-- PG 通用：updated_at 自动设为 NOW()（对应 MySQL ON UPDATE CURRENT_TIMESTAMP）
-- 用法：CREATE TABLE 之后执行 SELECT tg_set_updated_at('table_name');
-- ------------------------------------------------------------------------------
CREATE OR REPLACE FUNCTION tg_set_updated_at()
RETURNS TRIGGER LANGUAGE plpgsql AS $$
BEGIN
  NEW.updated_at := CURRENT_TIMESTAMP(0);
  RETURN NEW;
END; $$;

CREATE OR REPLACE PROCEDURE set_table_updated_at_trigger(tbl text) LANGUAGE plpgsql AS $$
DECLARE tg_name text := 'trg_' || tbl || '_set_updated_at';
BEGIN
  EXECUTE format('DROP TRIGGER IF EXISTS %I ON %I', tg_name, tbl);
  EXECUTE format('CREATE TRIGGER %I BEFORE UPDATE ON %I
                  FOR EACH ROW EXECUTE FUNCTION tg_set_updated_at()', tg_name, tbl);
END; $$;

-- ------------------------------------------------------------------------------
-- 通用：ENUM 类型（与 MySQL ENUM 对应，PG 原生 CHECK + 枚举语义）
-- 为与 MySQL 版本保持 VARCHAR(xx) 可移植，我们仍用 VARCHAR + CHECK，
-- 下面 2 个 ENUM 仅用于语义更清晰的考勤类型与性别（可选）
-- ------------------------------------------------------------------------------
-- CREATE TYPE performer_gender AS ENUM ('男','女','其他');
-- CREATE TYPE attendance_category AS ENUM ('full','night','double','half','公休','rest',
--   'SL','PL','BL','ML','AL','absent','rainout','leave','outing','study','business','injury');

-- ------------------------------------------------------------------------------
-- 批次 1：权限模块基础（8 张）—— 与 MySQL 完全对齐
-- ------------------------------------------------------------------------------
CREATE TABLE IF NOT EXISTS accounts_v2 (
  id                  VARCHAR(32)   PRIMARY KEY,
  username            VARCHAR(64)   NOT NULL UNIQUE,
  password_hash       VARCHAR(255)  NOT NULL,
  real_name           VARCHAR(50)   NOT NULL,
  role                VARCHAR(32)   NOT NULL DEFAULT 'staff',
  phone               VARCHAR(20),
  email               VARCHAR(128),
  avatar_url          VARCHAR(500),
  last_login_at       TIMESTAMP(0),
  last_login_ip       VARCHAR(45),
  force_pwd_change    BOOLEAN       NOT NULL DEFAULT TRUE,
  failed_login_count  INTEGER       NOT NULL DEFAULT 0,
  locked_until        TIMESTAMP(0),
  totp_secret         VARCHAR(64),
  status              VARCHAR(20)   NOT NULL DEFAULT 'active',
  created_at          TIMESTAMP(0)  NOT NULL DEFAULT CURRENT_TIMESTAMP(0),
  updated_at          TIMESTAMP(0)  NOT NULL DEFAULT CURRENT_TIMESTAMP(0),
  created_by          VARCHAR(32),
  updated_by          VARCHAR(32),
  _ts                 BIGINT        NOT NULL
);
CALL set_table_updated_at_trigger('accounts_v2');
COMMENT ON TABLE accounts_v2 IS '后台账号表 (M-14 初始超管 bcrypt+force_pwd_change)';

CREATE TABLE IF NOT EXISTS roles (
  id                  VARCHAR(32)   PRIMARY KEY,
  name                VARCHAR(50)   NOT NULL UNIQUE,
  description         VARCHAR(200),
  level               INTEGER       NOT NULL DEFAULT 100,
  status              VARCHAR(20)   NOT NULL DEFAULT 'active',
  created_at          TIMESTAMP(0)  NOT NULL DEFAULT CURRENT_TIMESTAMP(0),
  updated_at          TIMESTAMP(0)  NOT NULL DEFAULT CURRENT_TIMESTAMP(0),
  created_by          VARCHAR(32),
  updated_by          VARCHAR(32),
  _ts                 BIGINT        NOT NULL
);
CALL set_table_updated_at_trigger('roles');

CREATE TABLE IF NOT EXISTS permissions (
  id                  VARCHAR(32)   PRIMARY KEY,
  code                VARCHAR(80)   NOT NULL UNIQUE,
  name                VARCHAR(80)   NOT NULL,
  module              VARCHAR(32)   NOT NULL,
  description         VARCHAR(200),
  level_require       INTEGER       NOT NULL DEFAULT 100,
  status              VARCHAR(20)   NOT NULL DEFAULT 'active',
  created_at          TIMESTAMP(0)  NOT NULL DEFAULT CURRENT_TIMESTAMP(0),
  updated_at          TIMESTAMP(0)  NOT NULL DEFAULT CURRENT_TIMESTAMP(0),
  created_by          VARCHAR(32),
  updated_by          VARCHAR(32),
  _ts                 BIGINT        NOT NULL
);
CALL set_table_updated_at_trigger('permissions');

CREATE TABLE IF NOT EXISTS role_permissions (
  id                  VARCHAR(32)   PRIMARY KEY,
  role_id             VARCHAR(32)   NOT NULL,
  permission_code     VARCHAR(80)   NOT NULL,
  created_at          TIMESTAMP(0)  NOT NULL DEFAULT CURRENT_TIMESTAMP(0),
  created_by          VARCHAR(32),
  _ts                 BIGINT        NOT NULL,
  CONSTRAINT uk_role_perm UNIQUE (role_id, permission_code)
);

CREATE TABLE IF NOT EXISTS user_roles (
  id                  VARCHAR(32)   PRIMARY KEY,
  account_id          VARCHAR(32)   NOT NULL,
  role_id             VARCHAR(32)   NOT NULL,
  assigned_at         TIMESTAMP(0)  NOT NULL DEFAULT CURRENT_TIMESTAMP(0),
  assigned_by         VARCHAR(32),
  _ts                 BIGINT        NOT NULL,
  CONSTRAINT uk_user_role UNIQUE (account_id, role_id)
);

CREATE TABLE IF NOT EXISTS admin_sessions (
  id                  VARCHAR(64)   PRIMARY KEY,
  account_id          VARCHAR(32)   NOT NULL,
  ip_address          VARCHAR(45),
  user_agent          VARCHAR(500),
  expires_at          TIMESTAMP(0)  NOT NULL,
  issued_at           TIMESTAMP(0)  NOT NULL DEFAULT CURRENT_TIMESTAMP(0),
  last_seen_at        TIMESTAMP(0),
  device_fingerprint  VARCHAR(128),
  revoked             BOOLEAN       NOT NULL DEFAULT FALSE,
  _ts                 BIGINT        NOT NULL
);
CREATE INDEX IF NOT EXISTS idx_sess_expires ON admin_sessions(expires_at);

CREATE TABLE IF NOT EXISTS audit_logs (
  id                  VARCHAR(32)   PRIMARY KEY,
  account_id          VARCHAR(32),
  username_snapshot   VARCHAR(64)   NOT NULL,
  action              VARCHAR(64)   NOT NULL,
  module              VARCHAR(32)   NOT NULL,
  target_table        VARCHAR(64),
  target_id           VARCHAR(32),
  ip_address          VARCHAR(45),
  user_agent          VARCHAR(500),
  request_id          VARCHAR(64),
  before_snapshot     JSONB,
  after_snapshot      JSONB,
  diff_summary        VARCHAR(500),
  severity            VARCHAR(16)   NOT NULL DEFAULT 'info',
  action_ts           TIMESTAMP(0)  NOT NULL DEFAULT CURRENT_TIMESTAMP(0),
  _ts                 BIGINT        NOT NULL
);
CREATE INDEX IF NOT EXISTS idx_audit_user_ts ON audit_logs(account_id, action_ts DESC);
COMMENT ON TABLE audit_logs IS 'E-2 审计日志 · 财务作废/越权403/备份下载必留痕';

CREATE TABLE IF NOT EXISTS login_attempts (
  id                  BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  username            VARCHAR(64),
  ip_address          VARCHAR(45)   NOT NULL,
  success             BOOLEAN       NOT NULL,
  fail_reason         VARCHAR(64),
  attempted_at        TIMESTAMP(0)  NOT NULL DEFAULT CURRENT_TIMESTAMP(0),
  user_agent          VARCHAR(500),
  _ts                 BIGINT        NOT NULL
);
CREATE INDEX IF NOT EXISTS idx_login_ip_ts ON login_attempts(ip_address, attempted_at);

-- ------------------------------------------------------------------------------
-- 批次 2：系统/配置（3 张）
-- ------------------------------------------------------------------------------
CREATE TABLE IF NOT EXISTS settings (
  id                  VARCHAR(64)   PRIMARY KEY,
  key                 VARCHAR(100)  NOT NULL UNIQUE,
  value               TEXT          NOT NULL,
  value_type          VARCHAR(16)   NOT NULL DEFAULT 'string',
  "group"             VARCHAR(32)   NOT NULL DEFAULT 'general',
  description         VARCHAR(200),
  is_public           BOOLEAN       NOT NULL DEFAULT FALSE,
  updated_at          TIMESTAMP(0)  NOT NULL DEFAULT CURRENT_TIMESTAMP(0),
  updated_by          VARCHAR(32),
  _ts                 BIGINT        NOT NULL
);
CALL set_table_updated_at_trigger('settings');
COMMENT ON TABLE settings IS '系统参数';

CREATE TABLE IF NOT EXISTS system_backups (
  id                  VARCHAR(32)   PRIMARY KEY,
  filename            VARCHAR(200)  NOT NULL,
  size_bytes          BIGINT        NOT NULL,
  backup_type         VARCHAR(16)   NOT NULL DEFAULT 'daily',
  hash_sha256         VARCHAR(64)   NOT NULL,
  hash_md5            VARCHAR(32),
  storage_location    VARCHAR(16)   NOT NULL DEFAULT 'local',
  oss_object_key      VARCHAR(500),
  status              VARCHAR(16)   NOT NULL DEFAULT 'ok',
  integrity_ok        BOOLEAN       NOT NULL DEFAULT TRUE,
  downloaded_count    INTEGER       NOT NULL DEFAULT 0,
  created_by          VARCHAR(32),
  created_at          TIMESTAMP(0)  NOT NULL DEFAULT CURRENT_TIMESTAMP(0),
  expire_at           TIMESTAMP(0),
  _ts                 BIGINT        NOT NULL
);
CREATE INDEX IF NOT EXISTS idx_backup_ts ON system_backups(created_at DESC);

CREATE TABLE IF NOT EXISTS data_migrations (
  id                  VARCHAR(64)   PRIMARY KEY,
  batch               INTEGER       NOT NULL DEFAULT 1,
  description         VARCHAR(200),
  executed_by         VARCHAR(32),
  expected_row_count  INTEGER,
  actual_row_count    INTEGER,
  dry_run             BOOLEAN       NOT NULL DEFAULT FALSE,
  conflicts_json      JSONB,
  signature_sha256    VARCHAR(64),
  status              VARCHAR(16)   NOT NULL DEFAULT 'success',
  executed_at         TIMESTAMP(0)  NOT NULL DEFAULT CURRENT_TIMESTAMP(0),
  _ts                 BIGINT        NOT NULL
);

-- ------------------------------------------------------------------------------
-- 批次 3：主数据 · 演员/剧目/道具/内容（6 张）
-- ------------------------------------------------------------------------------
CREATE TABLE IF NOT EXISTS performers_db_v1 (
  id                  VARCHAR(32)   PRIMARY KEY,
  real_name           VARCHAR(50)   NOT NULL,
  stage_name          VARCHAR(50),
  gender              VARCHAR(8)    NOT NULL CHECK (gender IN ('男','女','其他')),
  birth_date          DATE,
  id_card_no          VARCHAR(18),
  phone               VARCHAR(20),
  emergency_contact   VARCHAR(50),
  emergency_phone     VARCHAR(20),
  crew_category       VARCHAR(32)   NOT NULL,
  rank_grade          VARCHAR(8)    NOT NULL DEFAULT 'C',
  join_date           DATE,
  leave_date          DATE,
  base_daily_wage     NUMERIC(10,2) NOT NULL DEFAULT 0,
  bank_card_no        VARCHAR(30),
  bank_name           VARCHAR(50),
  wechat_open_id      VARCHAR(64),
  avatar_url          VARCHAR(500),
  performer_type      VARCHAR(16)   NOT NULL DEFAULT 'employee',
  resume_text         TEXT,
  remark              TEXT,
  status              VARCHAR(20)   NOT NULL DEFAULT 'active',
  created_at          TIMESTAMP(0)  NOT NULL DEFAULT CURRENT_TIMESTAMP(0),
  updated_at          TIMESTAMP(0)  NOT NULL DEFAULT CURRENT_TIMESTAMP(0),
  created_by          VARCHAR(32),
  updated_by          VARCHAR(32),
  _ts                 BIGINT        NOT NULL
);
CALL set_table_updated_at_trigger('performers_db_v1');
COMMENT ON TABLE performers_db_v1 IS '演职人员花名册';

CREATE TABLE IF NOT EXISTS plays (
  id                  VARCHAR(32)   PRIMARY KEY,
  title               VARCHAR(100)  NOT NULL,
  subtitle            VARCHAR(200),
  alias               VARCHAR(200),
  genre               VARCHAR(32)   NOT NULL DEFAULT '传统本戏',
  duration_minutes    INTEGER,
  cast_min_count      INTEGER       NOT NULL DEFAULT 10,
  difficulty_level    SMALLINT      NOT NULL DEFAULT 3,
  premiere_year       INTEGER,
  author              VARCHAR(100),
  director            VARCHAR(100),
  composer            VARCHAR(100),
  synopsis            TEXT,
  highlights          TEXT,
  poster_url          VARCHAR(500),
  gallery_urls        JSONB,
  repertoire_status   VARCHAR(20)   NOT NULL DEFAULT 'repertoire',
  price_standard      NUMERIC(12,2) NOT NULL DEFAULT 0,
  tag_list            JSONB,
  sort_order          INTEGER       NOT NULL DEFAULT 100,
  is_public           BOOLEAN       NOT NULL DEFAULT TRUE,
  view_count          INTEGER       NOT NULL DEFAULT 0,
  status              VARCHAR(20)   NOT NULL DEFAULT 'active',
  created_at          TIMESTAMP(0)  NOT NULL DEFAULT CURRENT_TIMESTAMP(0),
  updated_at          TIMESTAMP(0)  NOT NULL DEFAULT CURRENT_TIMESTAMP(0),
  created_by          VARCHAR(32),
  updated_by          VARCHAR(32),
  _ts                 BIGINT        NOT NULL
);
CALL set_table_updated_at_trigger('plays');
COMMENT ON TABLE plays IS '剧目库';

CREATE TABLE IF NOT EXISTS play_casts (
  id                  VARCHAR(32)   PRIMARY KEY,
  play_id             VARCHAR(32)   NOT NULL,
  role_name           VARCHAR(50)   NOT NULL,
  role_type           VARCHAR(32),
  performer_id        VARCHAR(32),
  alternate_ids       JSONB,
  sort_order          INTEGER       NOT NULL DEFAULT 50,
  remark              VARCHAR(200),
  created_at          TIMESTAMP(0)  NOT NULL DEFAULT CURRENT_TIMESTAMP(0),
  updated_at          TIMESTAMP(0)  NOT NULL DEFAULT CURRENT_TIMESTAMP(0),
  created_by          VARCHAR(32),
  updated_by          VARCHAR(32),
  _ts                 BIGINT        NOT NULL
);
CALL set_table_updated_at_trigger('play_casts');
CREATE INDEX IF NOT EXISTS idx_pc_play ON play_casts(play_id);

CREATE TABLE IF NOT EXISTS inventory_items (
  id                  VARCHAR(32)   PRIMARY KEY,
  category            VARCHAR(32)   NOT NULL,
  name                VARCHAR(100)  NOT NULL,
  spec                VARCHAR(200),
  play_id             VARCHAR(32),
  qty_on_hand         INTEGER       NOT NULL DEFAULT 0,
  qty_available       INTEGER       NOT NULL DEFAULT 0,
  qty_loaned          INTEGER       NOT NULL DEFAULT 0,
  unit                VARCHAR(10)   NOT NULL DEFAULT '件',
  unit_price          NUMERIC(10,2) DEFAULT 0,
  total_value         NUMERIC(12,2) DEFAULT 0,
  storage_location    VARCHAR(100),
  purchase_date       DATE,
  supplier            VARCHAR(100),
  condition_level     VARCHAR(16)   NOT NULL DEFAULT 'ok',
  last_inventory_ts   TIMESTAMP(0),
  img_url             VARCHAR(500),
  remark              TEXT,
  status              VARCHAR(20)   NOT NULL DEFAULT 'active',
  created_at          TIMESTAMP(0)  NOT NULL DEFAULT CURRENT_TIMESTAMP(0),
  updated_at          TIMESTAMP(0)  NOT NULL DEFAULT CURRENT_TIMESTAMP(0),
  created_by          VARCHAR(32),
  updated_by          VARCHAR(32),
  _ts                 BIGINT        NOT NULL
);
CALL set_table_updated_at_trigger('inventory_items');
CREATE INDEX IF NOT EXISTS idx_inv_cat ON inventory_items(category);

CREATE TABLE IF NOT EXISTS inventory_records (
  id                  VARCHAR(32)   PRIMARY KEY,
  item_id             VARCHAR(32)   NOT NULL,
  op_type             VARCHAR(16)   NOT NULL,
  qty_change          INTEGER       NOT NULL,
  op_date             DATE          NOT NULL,
  operator_id         VARCHAR(32),
  related_schedule_id VARCHAR(32),
  unit_price          NUMERIC(10,2),
  supplier_or_person  VARCHAR(100),
  attachment_url      VARCHAR(500),
  remark              VARCHAR(500),
  created_at          TIMESTAMP(0)  NOT NULL DEFAULT CURRENT_TIMESTAMP(0),
  created_by          VARCHAR(32),
  _ts                 BIGINT        NOT NULL
);
CREATE INDEX IF NOT EXISTS idx_invrec_item ON inventory_records(item_id, op_date);

CREATE TABLE IF NOT EXISTS content_v2 (
  id                  VARCHAR(32)   PRIMARY KEY,
  type                VARCHAR(32)   NOT NULL,
  title               VARCHAR(200)  NOT NULL,
  slug                VARCHAR(100),
  cover_url           VARCHAR(500),
  summary             VARCHAR(500),
  body_html           TEXT,
  author              VARCHAR(50),
  source              VARCHAR(100),
  publish_date        DATE,
  publish_status      VARCHAR(16)   NOT NULL DEFAULT 'draft',
  is_hot              BOOLEAN       NOT NULL DEFAULT FALSE,
  sort_order          INTEGER       NOT NULL DEFAULT 100,
  lang                VARCHAR(8)    NOT NULL DEFAULT 'zh-CN',
  meta_keywords       VARCHAR(200),
  meta_description    VARCHAR(500),
  view_count          INTEGER       NOT NULL DEFAULT 0,
  status              VARCHAR(20)   NOT NULL DEFAULT 'active',
  created_at          TIMESTAMP(0)  NOT NULL DEFAULT CURRENT_TIMESTAMP(0),
  updated_at          TIMESTAMP(0)  NOT NULL DEFAULT CURRENT_TIMESTAMP(0),
  created_by          VARCHAR(32),
  updated_by          VARCHAR(32),
  _ts                 BIGINT        NOT NULL
);
CALL set_table_updated_at_trigger('content_v2');
CREATE INDEX IF NOT EXISTS idx_ct_type_status ON content_v2(type, publish_status, publish_date DESC);

-- ------------------------------------------------------------------------------
-- 批次 4：客户 + 预约（上游）—— 6 张
-- ------------------------------------------------------------------------------
CREATE TABLE IF NOT EXISTS customers_v1 (
  id                  VARCHAR(32)   PRIMARY KEY,
  customer_name       VARCHAR(100)  NOT NULL,
  customer_type       VARCHAR(16)   NOT NULL DEFAULT 'organization',
  organization        VARCHAR(200),
  contact_person      VARCHAR(50)   NOT NULL,
  phone               VARCHAR(20)   NOT NULL,
  alt_phone           VARCHAR(20),
  wechat              VARCHAR(50),
  email               VARCHAR(128),
  address             VARCHAR(500),
  id_card_no          VARCHAR(18),
  business_license    VARCHAR(50),
  tag_list            JSONB,
  total_orders        INTEGER       NOT NULL DEFAULT 0,
  total_shows         INTEGER       NOT NULL DEFAULT 0,
  total_revenue       NUMERIC(14,2) NOT NULL DEFAULT 0,
  credit_level        VARCHAR(8)    NOT NULL DEFAULT 'A',
  source_channel      VARCHAR(32),
  remark              TEXT,
  status              VARCHAR(20)   NOT NULL DEFAULT 'active',
  created_at          TIMESTAMP(0)  NOT NULL DEFAULT CURRENT_TIMESTAMP(0),
  updated_at          TIMESTAMP(0)  NOT NULL DEFAULT CURRENT_TIMESTAMP(0),
  created_by          VARCHAR(32),
  updated_by          VARCHAR(32),
  _ts                 BIGINT        NOT NULL
);
CALL set_table_updated_at_trigger('customers_v1');
CREATE INDEX IF NOT EXISTS idx_cust_name_org ON customers_v1(customer_name, organization);
CREATE INDEX IF NOT EXISTS idx_cust_phone    ON customers_v1(phone);

CREATE TABLE IF NOT EXISTS customer_contacts (
  id                  VARCHAR(32)   PRIMARY KEY,
  customer_id         VARCHAR(32)   NOT NULL,
  name                VARCHAR(50)   NOT NULL,
  title               VARCHAR(50),
  phone               VARCHAR(20)   NOT NULL,
  wechat              VARCHAR(50),
  email               VARCHAR(128),
  is_primary          BOOLEAN       NOT NULL DEFAULT TRUE,
  remark              VARCHAR(200),
  created_at          TIMESTAMP(0)  NOT NULL DEFAULT CURRENT_TIMESTAMP(0),
  created_by          VARCHAR(32),
  _ts                 BIGINT        NOT NULL
);

CREATE TABLE IF NOT EXISTS customer_tags (
  id                  VARCHAR(32)   PRIMARY KEY,
  customer_id         VARCHAR(32)   NOT NULL,
  tag                 VARCHAR(32)   NOT NULL,
  tagged_at           TIMESTAMP(0)  NOT NULL DEFAULT CURRENT_TIMESTAMP(0),
  tagged_by           VARCHAR(32),
  _ts                 BIGINT        NOT NULL,
  CONSTRAINT uk_cust_tag UNIQUE (customer_id, tag)
);

CREATE TABLE IF NOT EXISTS appointments (
  id                  VARCHAR(32)   PRIMARY KEY,
  customer_name       VARCHAR(100)  NOT NULL,
  phone               VARCHAR(20)   NOT NULL,
  organization        VARCHAR(200),
  shows               INTEGER       NOT NULL DEFAULT 1 CHECK (shows >= 1),
  selected_plays      JSONB,
  preferred_start_date DATE,
  performance_type    VARCHAR(32),
  venue               VARCHAR(300),
  audience_scale      VARCHAR(16),
  budget_range        VARCHAR(16),
  remarks             TEXT,
  source              VARCHAR(32)   NOT NULL DEFAULT 'online',
  verified_phone      BOOLEAN       NOT NULL DEFAULT FALSE,
  captcha_passed      BOOLEAN       NOT NULL DEFAULT FALSE,
  status              VARCHAR(20)   NOT NULL DEFAULT 'pending',
  reject_reason       VARCHAR(500),
  audited_by          VARCHAR(32),
  audited_at          TIMESTAMP(0),
  linked_customer_id  VARCHAR(32),
  linked_order_id     VARCHAR(32),
  assigned_staff      VARCHAR(32),
  first_contact_at    TIMESTAMP(0),
  last_contact_at     TIMESTAMP(0),
  contact_count       INTEGER       NOT NULL DEFAULT 0,
  request_id          VARCHAR(64),
  client_ip           VARCHAR(45),
  client_ua           VARCHAR(500),
  created_at          TIMESTAMP(0)  NOT NULL DEFAULT CURRENT_TIMESTAMP(0),
  updated_at          TIMESTAMP(0)  NOT NULL DEFAULT CURRENT_TIMESTAMP(0),
  created_by          VARCHAR(32),
  updated_by          VARCHAR(32),
  _ts                 BIGINT        NOT NULL
);
CALL set_table_updated_at_trigger('appointments');
CREATE INDEX IF NOT EXISTS idx_appt_phone_status ON appointments(phone, status, created_at);
CREATE INDEX IF NOT EXISTS idx_appt_status_date ON appointments(status, preferred_start_date);

CREATE TABLE IF NOT EXISTS appointment_plays (
  id                  VARCHAR(32)   PRIMARY KEY,
  appointment_id      VARCHAR(32)   NOT NULL,
  play_id             VARCHAR(32),
  play_title_snapshot VARCHAR(100)  NOT NULL,
  play_count          INTEGER       NOT NULL DEFAULT 1,
  preferred_time      VARCHAR(100),
  remark              VARCHAR(300),
  created_at          TIMESTAMP(0)  NOT NULL DEFAULT CURRENT_TIMESTAMP(0),
  _ts                 BIGINT        NOT NULL
);

CREATE TABLE IF NOT EXISTS appointment_audit (
  id                  VARCHAR(32)   PRIMARY KEY,
  appointment_id      VARCHAR(32)   NOT NULL,
  action              VARCHAR(32)   NOT NULL,
  actor_id            VARCHAR(32),
  detail_json         JSONB,
  action_ts           TIMESTAMP(0)  NOT NULL DEFAULT CURRENT_TIMESTAMP(0),
  _ts                 BIGINT        NOT NULL
);
CREATE INDEX IF NOT EXISTS idx_apptaudit_aid ON appointment_audit(appointment_id, action_ts);

-- ------------------------------------------------------------------------------
-- 批次 5：订单 + 档期 + 演员表 —— 8 张
-- ------------------------------------------------------------------------------
CREATE TABLE IF NOT EXISTS orders (
  id                  VARCHAR(32)   PRIMARY KEY,
  order_no            VARCHAR(32)   NOT NULL UNIQUE,
  order_date          DATE          NOT NULL,
  customer_id         VARCHAR(32)   NOT NULL,
  customer_snapshot   JSONB         NOT NULL,
  title               VARCHAR(200)  NOT NULL,
  shows               INTEGER       NOT NULL DEFAULT 1,
  start_date          DATE,
  end_date            DATE,
  venue               VARCHAR(300),
  performance_type    VARCHAR(32),
  price_total         NUMERIC(12,2) NOT NULL DEFAULT 0,
  discount_amount     NUMERIC(12,2) NOT NULL DEFAULT 0,
  tax_amount          NUMERIC(12,2) NOT NULL DEFAULT 0,
  other_charges       NUMERIC(12,2) NOT NULL DEFAULT 0,
  grand_total         NUMERIC(12,2) NOT NULL DEFAULT 0,
  deposit_amount      NUMERIC(12,2) NOT NULL DEFAULT 0,
  paid_amount         NUMERIC(12,2) NOT NULL DEFAULT 0,
  unpaid_amount       NUMERIC(12,2) NOT NULL DEFAULT 0,
  discount_rule       VARCHAR(100),
  contract_url        VARCHAR(500),
  contract_signed_date DATE,
  status              VARCHAR(20)   NOT NULL DEFAULT 'draft',
  close_status        VARCHAR(16)   NOT NULL DEFAULT 'open',
  source              VARCHAR(32),
  source_appointment_id VARCHAR(32),
  assigned_sales      VARCHAR(32),
  internal_remark     TEXT,
  customer_remark     TEXT,
  created_at          TIMESTAMP(0)  NOT NULL DEFAULT CURRENT_TIMESTAMP(0),
  updated_at          TIMESTAMP(0)  NOT NULL DEFAULT CURRENT_TIMESTAMP(0),
  created_by          VARCHAR(32),
  updated_by          VARCHAR(32),
  _ts                 BIGINT        NOT NULL
);
CALL set_table_updated_at_trigger('orders');
CREATE INDEX IF NOT EXISTS idx_order_status_date ON orders(status, order_date DESC);
CREATE INDEX IF NOT EXISTS idx_order_customer    ON orders(customer_id);

CREATE TABLE IF NOT EXISTS order_items (
  id                  VARCHAR(32)   PRIMARY KEY,
  order_id            VARCHAR(32)   NOT NULL,
  item_type           VARCHAR(32)   NOT NULL,
  play_id             VARCHAR(32),
  title               VARCHAR(200)  NOT NULL,
  description         VARCHAR(500),
  qty                 INTEGER       NOT NULL DEFAULT 1,
  unit_price          NUMERIC(12,2) NOT NULL DEFAULT 0,
  discount_rate       NUMERIC(5,4)  NOT NULL DEFAULT 1.0000,
  line_total          NUMERIC(12,2) NOT NULL DEFAULT 0,
  tax_rate            NUMERIC(5,4)  NOT NULL DEFAULT 0.0600,
  performance_date    DATE,
  sort_order          INTEGER       NOT NULL DEFAULT 10,
  created_at          TIMESTAMP(0)  NOT NULL DEFAULT CURRENT_TIMESTAMP(0),
  created_by          VARCHAR(32),
  _ts                 BIGINT        NOT NULL
);

CREATE TABLE IF NOT EXISTS fin_payments_v1 (
  id                  VARCHAR(32)   PRIMARY KEY,
  order_id            VARCHAR(32),
  payment_no          VARCHAR(32)   NOT NULL UNIQUE,
  payer_name          VARCHAR(100),
  payer_account       VARCHAR(50),
  pay_method          VARCHAR(20)   NOT NULL,
  pay_channel         VARCHAR(16),
  amount              NUMERIC(12,2) NOT NULL,
  pay_date            DATE          NOT NULL,
  pay_time            TIME,
  bank_slip_url       VARCHAR(500),
  status              VARCHAR(16)   NOT NULL DEFAULT 'confirmed',
  wxpay_transaction_id VARCHAR(64),
  wxpay_notify_raw    JSONB,
  operator_id         VARCHAR(32),
  reconciled          BOOLEAN       NOT NULL DEFAULT FALSE,
  ledger_posted       BOOLEAN       NOT NULL DEFAULT TRUE,
  remark              VARCHAR(500),
  created_at          TIMESTAMP(0)  NOT NULL DEFAULT CURRENT_TIMESTAMP(0),
  created_by          VARCHAR(32),
  _ts                 BIGINT        NOT NULL
);
CREATE INDEX IF NOT EXISTS idx_pay_order ON fin_payments_v1(order_id, pay_date);

CREATE TABLE IF NOT EXISTS order_refunds (
  id                  VARCHAR(32)   PRIMARY KEY,
  order_id            VARCHAR(32)   NOT NULL,
  refund_no           VARCHAR(32)   NOT NULL UNIQUE,
  amount              NUMERIC(12,2) NOT NULL,
  reason              VARCHAR(500)  NOT NULL,
  payback_method      VARCHAR(20),
  payback_date        DATE,
  status              VARCHAR(16)   NOT NULL DEFAULT 'pending',
  ledger_posted       BOOLEAN       NOT NULL DEFAULT FALSE,
  approver_id         VARCHAR(32),
  created_at          TIMESTAMP(0)  NOT NULL DEFAULT CURRENT_TIMESTAMP(0),
  created_by          VARCHAR(32),
  _ts                 BIGINT        NOT NULL
);

CREATE TABLE IF NOT EXISTS schedules_v2 (
  id                  VARCHAR(32)   PRIMARY KEY,
  schedule_no         VARCHAR(32)   NOT NULL UNIQUE,
  order_id            VARCHAR(32),
  title               VARCHAR(200)  NOT NULL,
  schedule_date_start DATE          NOT NULL,
  schedule_date_end   DATE          NOT NULL,
  days_duration       INTEGER       NOT NULL DEFAULT 1,
  total_shows         INTEGER       NOT NULL DEFAULT 1,
  venue               VARCHAR(300)   NOT NULL,
  venue_lat           NUMERIC(10,7),
  venue_lng           NUMERIC(10,7),
  audience_estimated  INTEGER,
  performance_type    VARCHAR(32),
  daily_show_plan     JSONB,
  transport_plan      TEXT,
  accommodation_plan  TEXT,
  stage_requirements  TEXT,
  status              VARCHAR(20)   NOT NULL DEFAULT 'tentative',
  weather_forecast_snapshot JSONB,
  conflict_checked_at TIMESTAMP(0),
  cast_sheet_id       VARCHAR(32),
  remark              TEXT,
  created_at          TIMESTAMP(0)  NOT NULL DEFAULT CURRENT_TIMESTAMP(0),
  updated_at          TIMESTAMP(0)  NOT NULL DEFAULT CURRENT_TIMESTAMP(0),
  created_by          VARCHAR(32),
  updated_by          VARCHAR(32),
  _ts                 BIGINT        NOT NULL
);
CALL set_table_updated_at_trigger('schedules_v2');
CREATE INDEX IF NOT EXISTS idx_sched_range  ON schedules_v2(schedule_date_start, schedule_date_end, status);
CREATE INDEX IF NOT EXISTS idx_sched_status ON schedules_v2(status, schedule_date_start);
COMMENT ON TABLE schedules_v2 IS '档期排班 (M-1 Redis 乐观锁 冲突检测)';

CREATE TABLE IF NOT EXISTS schedule_venues (
  id                  VARCHAR(32)   PRIMARY KEY,
  schedule_id         VARCHAR(32)   NOT NULL,
  venue_name          VARCHAR(200)  NOT NULL,
  venue_address       VARCHAR(300),
  show_date           DATE          NOT NULL,
  show_time_slot      VARCHAR(50),
  stage_type          VARCHAR(32),
  capacity_estimate   INTEGER,
  contact_person      VARCHAR(50),
  contact_phone       VARCHAR(20),
  remark              VARCHAR(500),
  _ts                 BIGINT        NOT NULL
);

CREATE TABLE IF NOT EXISTS cast_sheets_v1 (
  id                  VARCHAR(32)   PRIMARY KEY,
  schedule_id         VARCHAR(32),
  order_id            VARCHAR(32),
  apply_template_id   VARCHAR(32),
  title               VARCHAR(200)  NOT NULL,
  performance_date    DATE          NOT NULL,
  matinee_or_evening  VARCHAR(16)   NOT NULL DEFAULT '夜场',
  venue               VARCHAR(300),
  chief_director      VARCHAR(32),
  stage_manager       VARCHAR(32),
  show_plays          JSONB,
  total_cost_labor    NUMERIC(12,2) NOT NULL DEFAULT 0,
  total_cost_other    NUMERIC(12,2) NOT NULL DEFAULT 0,
  final_status        VARCHAR(16)   NOT NULL DEFAULT 'draft',
  finalized_by        VARCHAR(32),
  finalized_at        TIMESTAMP(0),
  print_count         INTEGER       NOT NULL DEFAULT 0,
  remark              TEXT,
  created_at          TIMESTAMP(0)  NOT NULL DEFAULT CURRENT_TIMESTAMP(0),
  updated_at          TIMESTAMP(0)  NOT NULL DEFAULT CURRENT_TIMESTAMP(0),
  created_by          VARCHAR(32),
  updated_by          VARCHAR(32),
  _ts                 BIGINT        NOT NULL
);
CALL set_table_updated_at_trigger('cast_sheets_v1');
CREATE INDEX IF NOT EXISTS idx_cs_schedule ON cast_sheets_v1(schedule_id);
COMMENT ON TABLE cast_sheets_v1 IS '演出当日演员表（cast-sheet.html A4打印）';

CREATE TABLE IF NOT EXISTS cast_sheet_crew (
  id                  VARCHAR(32)   PRIMARY KEY,
  cast_sheet_id       VARCHAR(32)   NOT NULL,
  performer_id        VARCHAR(32)   NOT NULL,
  performer_name_snap VARCHAR(50)   NOT NULL,
  crew_category_snap  VARCHAR(32)   NOT NULL,
  role_assigned       VARCHAR(100),
  play_id             VARCHAR(32),
  daily_wage          NUMERIC(10,2) NOT NULL DEFAULT 0,
  wage_reason         VARCHAR(200),
  transport_allowance NUMERIC(8,2) DEFAULT 0,
  meal_allowance      NUMERIC(8,2) DEFAULT 0,
  other_allowance     NUMERIC(8,2) DEFAULT 0,
  deduction_amount    NUMERIC(8,2) DEFAULT 0,
  deduction_reason    VARCHAR(200),
  net_amount          NUMERIC(10,2) NOT NULL DEFAULT 0,
  attendance_type     VARCHAR(16)   NOT NULL DEFAULT 'full',
  signed_in           BOOLEAN       NOT NULL DEFAULT FALSE,
  signed_at           TIMESTAMP(0),
  sign_ip             VARCHAR(45),
  sort_order          INTEGER       NOT NULL DEFAULT 50,
  section             VARCHAR(16)   NOT NULL DEFAULT '主演',
  remark              VARCHAR(300),
  created_at          TIMESTAMP(0)  NOT NULL DEFAULT CURRENT_TIMESTAMP(0),
  created_by          VARCHAR(32),
  _ts                 BIGINT        NOT NULL
);
CREATE INDEX IF NOT EXISTS idx_csc_cs ON cast_sheet_crew(cast_sheet_id);

-- ------------------------------------------------------------------------------
-- 批次 6：财务台账 + 发票 + 对账 + 欠款 + 工资批次/明细 + 工资规则 —— 7 张
-- ------------------------------------------------------------------------------
CREATE TABLE IF NOT EXISTS wage_rules_v1 (
  id                  VARCHAR(32)   PRIMARY KEY,
  rank_grade          VARCHAR(8)    NOT NULL UNIQUE,
  base_daily_standard  NUMERIC(10,2) NOT NULL,
  chief_role_allowance NUMERIC(8,2) NOT NULL DEFAULT 0,
  supporting_role_base NUMERIC(8,2) NOT NULL DEFAULT 0,
  ensemble_base       NUMERIC(8,2) NOT NULL DEFAULT 0,
  crew_band_base      NUMERIC(8,2) NOT NULL DEFAULT 0,
  tech_dancer_base    NUMERIC(8,2) NOT NULL DEFAULT 0,
  night_show_bonus    NUMERIC(6,2) NOT NULL DEFAULT 0,
  holiday_multiplier  NUMERIC(5,4)  NOT NULL DEFAULT 1.5000,
  transport_allowance NUMERIC(6,2) NOT NULL DEFAULT 30,
  meal_allowance      NUMERIC(6,2) NOT NULL DEFAULT 30,
  full_attendance_bonus NUMERIC(6,2) NOT NULL DEFAULT 200,
  performance_bonus_rate NUMERIC(5,4) NOT NULL DEFAULT 0.0500,
  effective_from_date DATE          NOT NULL,
  effective_to_date   DATE,
  status              VARCHAR(20)   NOT NULL DEFAULT 'active',
  created_at          TIMESTAMP(0)  NOT NULL DEFAULT CURRENT_TIMESTAMP(0),
  updated_by          VARCHAR(32),
  _ts                 BIGINT        NOT NULL
);

CREATE TABLE IF NOT EXISTS wage_batches_v1 (
  id                  VARCHAR(32)   PRIMARY KEY,
  batch_no            VARCHAR(32)   NOT NULL UNIQUE,
  payroll_month       VARCHAR(7)    NOT NULL,
  performers_count    INTEGER       NOT NULL DEFAULT 0,
  total_base_wage     NUMERIC(14,2) NOT NULL DEFAULT 0,
  total_bonus         NUMERIC(14,2) NOT NULL DEFAULT 0,
  total_allowance     NUMERIC(14,2) NOT NULL DEFAULT 0,
  total_deduction     NUMERIC(14,2) NOT NULL DEFAULT 0,
  total_tax_personal  NUMERIC(12,2) NOT NULL DEFAULT 0,
  total_social_emp    NUMERIC(12,2) NOT NULL DEFAULT 0,
  grand_total_net     NUMERIC(14,2) NOT NULL DEFAULT 0,
  engine_version      VARCHAR(16)   NOT NULL DEFAULT 'V2',
  calc_params_json    JSONB,
  calc_duration_ms    INTEGER,
  status              VARCHAR(16)   NOT NULL DEFAULT 'draft',
  pushed_finance_at   TIMESTAMP(0),
  posted_ledger_ids   JSONB,
  approver_id         VARCHAR(32),
  calc_log_url        VARCHAR(500),
  remark              TEXT,
  created_at          TIMESTAMP(0)  NOT NULL DEFAULT CURRENT_TIMESTAMP(0),
  updated_at          TIMESTAMP(0)  NOT NULL DEFAULT CURRENT_TIMESTAMP(0),
  created_by          VARCHAR(32),
  updated_by          VARCHAR(32),
  _ts                 BIGINT        NOT NULL
);
CALL set_table_updated_at_trigger('wage_batches_v1');

CREATE TABLE IF NOT EXISTS wage_items_v1 (
  id                  VARCHAR(32)   PRIMARY KEY,
  batch_id            VARCHAR(32)   NOT NULL,
  performer_id        VARCHAR(32)   NOT NULL,
  performer_snapshot  JSONB         NOT NULL,
  attendance_days_full NUMERIC(5,1) NOT NULL DEFAULT 0,
  attendance_days_half NUMERIC(5,1) NOT NULL DEFAULT 0,
  leave_sick_days     NUMERIC(5,1) NOT NULL DEFAULT 0,
  absent_days         INTEGER       NOT NULL DEFAULT 0,
  performance_shows   INTEGER       NOT NULL DEFAULT 0,
  base_wage           NUMERIC(12,2) NOT NULL DEFAULT 0,
  role_bonus          NUMERIC(10,2) NOT NULL DEFAULT 0,
  performance_bonus   NUMERIC(10,2) NOT NULL DEFAULT 0,
  full_attendance_bonus NUMERIC(8,2) NOT NULL DEFAULT 0,
  transport_allowance NUMERIC(10,2) NOT NULL DEFAULT 0,
  meal_allowance      NUMERIC(10,2) NOT NULL DEFAULT 0,
  holiday_allowance   NUMERIC(10,2) NOT NULL DEFAULT 0,
  other_bonus         NUMERIC(10,2) NOT NULL DEFAULT 0,
  accident_penalty    NUMERIC(10,2) NOT NULL DEFAULT 0,
  late_penalty        NUMERIC(10,2) NOT NULL DEFAULT 0,
  other_deduction     NUMERIC(10,2) NOT NULL DEFAULT 0,
  social_insurance_emp NUMERIC(10,2) NOT NULL DEFAULT 0,
  housing_fund_emp    NUMERIC(10,2) NOT NULL DEFAULT 0,
  personal_tax        NUMERIC(10,2) NOT NULL DEFAULT 0,
  gross_amount        NUMERIC(12,2) NOT NULL DEFAULT 0,
  total_deduction     NUMERIC(12,2) NOT NULL DEFAULT 0,
  net_amount          NUMERIC(12,2) NOT NULL DEFAULT 0,
  payslip_pdf_url     VARCHAR(500),
  payslip_sent        BOOLEAN       NOT NULL DEFAULT FALSE,
  payslip_sent_ts     TIMESTAMP(0),
  sign_confirmed      BOOLEAN       NOT NULL DEFAULT FALSE,
  remark              VARCHAR(500),
  created_at          TIMESTAMP(0)  NOT NULL DEFAULT CURRENT_TIMESTAMP(0),
  _ts                 BIGINT        NOT NULL,
  CONSTRAINT uk_wageitem_batch_staff UNIQUE (batch_id, performer_id)
);

CREATE TABLE IF NOT EXISTS fin_ledger_v1 (
  id                  VARCHAR(32)   PRIMARY KEY,
  voucher_no          VARCHAR(32)   NOT NULL UNIQUE,
  voucher_date        DATE          NOT NULL,
  voucher_type        VARCHAR(20)   NOT NULL,
  source_module       VARCHAR(16),
  source_id           VARCHAR(32),
  abstract            VARCHAR(200)  NOT NULL,
  debit_account_code  VARCHAR(16)   NOT NULL,
  debit_account_name  VARCHAR(50)   NOT NULL,
  debit_amount        NUMERIC(14,2) NOT NULL DEFAULT 0,
  credit_account_code VARCHAR(16)   NOT NULL,
  credit_account_name VARCHAR(50)   NOT NULL,
  credit_amount       NUMERIC(14,2) NOT NULL DEFAULT 0,
  amount_equal_check  BOOLEAN       NOT NULL DEFAULT TRUE,
  currency            VARCHAR(3)    NOT NULL DEFAULT 'CNY',
  related_party_name  VARCHAR(100),
  related_order_id    VARCHAR(32),
  related_wage_batch  VARCHAR(32),
  attachment_urls     JSONB,
  status              VARCHAR(16)   NOT NULL DEFAULT 'draft',
  is_void             BOOLEAN       NOT NULL DEFAULT FALSE,
  void_of_voucher_id  VARCHAR(32),
  void_reason         VARCHAR(300),
  maker_id            VARCHAR(32)   NOT NULL,
  checker_id          VARCHAR(32),
  poster_id           VARCHAR(32),
  posted_at           TIMESTAMP(0),
  fiscal_period       VARCHAR(7)    NOT NULL,
  is_reconciled       BOOLEAN       NOT NULL DEFAULT FALSE,
  reconcile_batch_id  VARCHAR(32),
  remark              TEXT,
  created_at          TIMESTAMP(0)  NOT NULL DEFAULT CURRENT_TIMESTAMP(0),
  updated_at          TIMESTAMP(0)  NOT NULL DEFAULT CURRENT_TIMESTAMP(0),
  created_by          VARCHAR(32),
  updated_by          VARCHAR(32),
  _ts                 BIGINT        NOT NULL
);
CALL set_table_updated_at_trigger('fin_ledger_v1');
CREATE INDEX IF NOT EXISTS idx_ledger_voucher_date ON fin_ledger_v1(voucher_date DESC, voucher_type);
CREATE INDEX IF NOT EXISTS idx_ledger_status_reconciled ON fin_ledger_v1(status, is_reconciled);
COMMENT ON TABLE fin_ledger_v1 IS '财务凭证（禁止物理删除！一律 is_void 红冲）';

CREATE TABLE IF NOT EXISTS fin_invoices_v1 (
  id                  VARCHAR(32)   PRIMARY KEY,
  invoice_no          VARCHAR(32)   NOT NULL UNIQUE,
  invoice_code        VARCHAR(32),
  invoice_type        VARCHAR(16)   NOT NULL,
  title_type          VARCHAR(16)   NOT NULL DEFAULT 'company',
  buyer_title         VARCHAR(200)  NOT NULL,
  buyer_tax_no        VARCHAR(20),
  buyer_address       VARCHAR(300),
  buyer_phone         VARCHAR(20),
  buyer_bank          VARCHAR(200),
  buyer_bank_account  VARCHAR(40),
  seller_title        VARCHAR(200)  NOT NULL,
  seller_tax_no       VARCHAR(20)   NOT NULL,
  invoice_date        DATE          NOT NULL,
  tax_rate            NUMERIC(5,4)  NOT NULL DEFAULT 0.0600,
  tax_excl_amount     NUMERIC(14,2) NOT NULL DEFAULT 0,
  tax_amount          NUMERIC(12,2) NOT NULL DEFAULT 0,
  total_amount        NUMERIC(14,2) NOT NULL DEFAULT 0,
  total_in_chinese    VARCHAR(100),
  items_json          JSONB,
  related_order_id    VARCHAR(32),
  related_payment_id  VARCHAR(32),
  pdf_url             VARCHAR(500),
  status              VARCHAR(16)   NOT NULL DEFAULT 'issued',
  red_of_invoice_id   VARCHAR(32),
  issuer_id           VARCHAR(32),
  remark              VARCHAR(500),
  created_at          TIMESTAMP(0)  NOT NULL DEFAULT CURRENT_TIMESTAMP(0),
  created_by          VARCHAR(32),
  _ts                 BIGINT        NOT NULL
);

CREATE TABLE IF NOT EXISTS fin_recons_v1 (
  id                  VARCHAR(32)   PRIMARY KEY,
  batch_no            VARCHAR(32)   NOT NULL UNIQUE,
  fiscal_period       VARCHAR(7)    NOT NULL,
  bank_account_name   VARCHAR(100)  NOT NULL,
  bank_account_no_last4 VARCHAR(4)  NOT NULL,
  bank_statement_date DATE          NOT NULL,
  book_balance        NUMERIC(14,2) NOT NULL,
  bank_balance        NUMERIC(14,2) NOT NULL,
  diff_amount         NUMERIC(14,2) NOT NULL DEFAULT 0,
  adjusted_book_balance NUMERIC(14,2) NOT NULL DEFAULT 0,
  reconciling_items_json JSONB,
  status              VARCHAR(16)   NOT NULL DEFAULT 'in_progress',
  matched_count       INTEGER       NOT NULL DEFAULT 0,
  unmatched_count     INTEGER       NOT NULL DEFAULT 0,
  reconciled_by       VARCHAR(32),
  approved_by         VARCHAR(32),
  completed_at        TIMESTAMP(0),
  remark              TEXT,
  created_at          TIMESTAMP(0)  NOT NULL DEFAULT CURRENT_TIMESTAMP(0),
  _ts                 BIGINT        NOT NULL
);

CREATE TABLE IF NOT EXISTS fin_debts_v1 (
  id                  VARCHAR(32)   PRIMARY KEY,
  order_id            VARCHAR(32),
  debtor_name         VARCHAR(100)  NOT NULL,
  debtor_contact      VARCHAR(50),
  debtor_phone        VARCHAR(20),
  original_amount     NUMERIC(14,2) NOT NULL,
  paid_amount         NUMERIC(14,2) NOT NULL DEFAULT 0,
  remaining_amount    NUMERIC(14,2) NOT NULL,
  due_date            DATE          NOT NULL,
  -- PG: 生成列 (MySQL DATEDIFF 对应 CURRENT_DATE - due_date)
  overdue_days        INTEGER GENERATED ALWAYS AS ((CURRENT_DATE - due_date)) STORED,
  last_remind_date    DATE,
  remind_count        INTEGER       NOT NULL DEFAULT 0,
  source              VARCHAR(32)   NOT NULL DEFAULT 'order_unpaid',
  dunning_progress    VARCHAR(16)   NOT NULL DEFAULT 'level1',
  guarantee_party     VARCHAR(100),
  attachments         JSONB,
  status              VARCHAR(16)   NOT NULL DEFAULT 'pending',
  assigned_staff      VARCHAR(32),
  alert_triggered     BOOLEAN       NOT NULL DEFAULT FALSE,
  remark              TEXT,
  created_at          TIMESTAMP(0)  NOT NULL DEFAULT CURRENT_TIMESTAMP(0),
  updated_at          TIMESTAMP(0)  NOT NULL DEFAULT CURRENT_TIMESTAMP(0),
  created_by          VARCHAR(32),
  updated_by          VARCHAR(32),
  _ts                 BIGINT        NOT NULL
);
CALL set_table_updated_at_trigger('fin_debts_v1');
COMMENT ON TABLE fin_debts_v1 IS '应收账款欠款追踪（M-6 逾期告警）';

-- ------------------------------------------------------------------------------
-- 批次 7：考勤 + 打卡 + 请假 + 加班 —— 4 张
-- ------------------------------------------------------------------------------
CREATE TABLE IF NOT EXISTS attendance_v1 (
  id                  VARCHAR(32)   PRIMARY KEY,
  staff_id            VARCHAR(32)   NOT NULL,
  attendance_date     DATE          NOT NULL,
  attendance_type     VARCHAR(16)   NOT NULL DEFAULT '公休',
  -- 虚拟列 attendance_month（MySQL DATE_FORMAT 对应 PG to_char）
  attendance_month    VARCHAR(7) GENERATED ALWAYS AS (to_char(attendance_date, 'YYYY-MM')) STORED,
  week_of_month       SMALLINT,
  related_schedule_id VARCHAR(32),
  related_cast_sheet  VARCHAR(32),
  shows_performed     INTEGER       NOT NULL DEFAULT 0,
  work_start          TIME,
  work_end            TIME,
  work_hours          NUMERIC(4,1),
  transport_allowance NUMERIC(8,2) DEFAULT 0,
  meal_allowance      NUMERIC(8,2) DEFAULT 0,
  rain_allowance      NUMERIC(8,2) DEFAULT 0,
  night_allowance     NUMERIC(8,2) DEFAULT 0,
  holiday_multiplier  NUMERIC(5,4) DEFAULT 1.0000,
  performance_bonus   NUMERIC(10,2) DEFAULT 0,
  accident_penalty    NUMERIC(10,2) DEFAULT 0,
  discipline_penalty  NUMERIC(10,2) DEFAULT 0,
  other_bonus         NUMERIC(10,2) DEFAULT 0,
  other_deduction     NUMERIC(10,2) DEFAULT 0,
  punch_count_ok      SMALLINT      NOT NULL DEFAULT 0,
  remark              VARCHAR(500),
  locked              BOOLEAN       NOT NULL DEFAULT FALSE,
  wage_batch_id       VARCHAR(32),
  created_at          TIMESTAMP(0)  NOT NULL DEFAULT CURRENT_TIMESTAMP(0),
  updated_at          TIMESTAMP(0)  NOT NULL DEFAULT CURRENT_TIMESTAMP(0),
  created_by          VARCHAR(32),
  updated_by          VARCHAR(32),
  _ts                 BIGINT        NOT NULL,
  CONSTRAINT uk_att_staff_date UNIQUE (staff_id, attendance_date)
);
CALL set_table_updated_at_trigger('attendance_v1');
CREATE INDEX IF NOT EXISTS idx_att_month ON attendance_v1(staff_id, attendance_month, attendance_type);
COMMENT ON TABLE attendance_v1 IS '每日考勤（月底算工资核心表）';

CREATE TABLE IF NOT EXISTS attendance_punch_records (
  id                  BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  staff_id            VARCHAR(32)   NOT NULL,
  attendance_date     DATE          NOT NULL,
  punch_type          VARCHAR(16)   NOT NULL,
  punch_time          TIME          NOT NULL,
  punch_method        VARCHAR(16)   NOT NULL,
  punch_lat           NUMERIC(10,7),
  punch_lng           NUMERIC(10,7),
  venue_radius_match  BOOLEAN,
  punch_img_url       VARCHAR(500),
  device_id           VARCHAR(64),
  client_ip           VARCHAR(45),
  is_late             BOOLEAN       NOT NULL DEFAULT FALSE,
  is_early_leave      BOOLEAN       NOT NULL DEFAULT FALSE,
  manual_corrected    BOOLEAN       NOT NULL DEFAULT FALSE,
  corrected_by        VARCHAR(32),
  corrected_reason    VARCHAR(200),
  created_at          TIMESTAMP(0)  NOT NULL DEFAULT CURRENT_TIMESTAMP(0),
  _ts                 BIGINT        NOT NULL
);
CREATE INDEX IF NOT EXISTS idx_punch_staff ON attendance_punch_records(staff_id, attendance_date, punch_type);

CREATE TABLE IF NOT EXISTS leave_applications (
  id                  VARCHAR(32)   PRIMARY KEY,
  staff_id            VARCHAR(32)   NOT NULL,
  leave_type          VARCHAR(16)   NOT NULL,
  date_from           DATE          NOT NULL,
  date_to             DATE          NOT NULL,
  days_count          NUMERIC(5,1)  NOT NULL,
  reason              VARCHAR(500)  NOT NULL,
  attachment_url      VARCHAR(500),
  status              VARCHAR(16)   NOT NULL DEFAULT 'pending',
  workflow_stage      VARCHAR(16)   NOT NULL DEFAULT 'hr',
  approver_hr         VARCHAR(32),
  approver_final      VARCHAR(32),
  approved_at         TIMESTAMP(0),
  attendance_posted   BOOLEAN       NOT NULL DEFAULT FALSE,
  remark              VARCHAR(300),
  created_at          TIMESTAMP(0)  NOT NULL DEFAULT CURRENT_TIMESTAMP(0),
  created_by          VARCHAR(32),
  _ts                 BIGINT        NOT NULL
);
CREATE INDEX IF NOT EXISTS idx_leave_staff ON leave_applications(staff_id, date_from);

CREATE TABLE IF NOT EXISTS overtime_records (
  id                  VARCHAR(32)   PRIMARY KEY,
  staff_id            VARCHAR(32)   NOT NULL,
  overtime_date       DATE          NOT NULL,
  overtime_type       VARCHAR(16)   NOT NULL,
  time_from           TIME,
  time_to             TIME,
  hours               NUMERIC(4,1)  NOT NULL,
  subsidy_per_hour    NUMERIC(8,2) DEFAULT 0,
  total_subsidy       NUMERIC(10,2) DEFAULT 0,
  meal_ticket_count   INTEGER DEFAULT 0,
  reason              VARCHAR(500),
  approved_by         VARCHAR(32),
  approved_at         TIMESTAMP(0),
  wage_posted         BOOLEAN       NOT NULL DEFAULT FALSE,
  created_at          TIMESTAMP(0)  NOT NULL DEFAULT CURRENT_TIMESTAMP(0),
  created_by          VARCHAR(32),
  _ts                 BIGINT        NOT NULL
);
CREATE INDEX IF NOT EXISTS idx_ot_staff ON overtime_records(staff_id, overtime_date);

-- ==============================================================================
-- 授权收尾：3 层数据库账号权限（M-2 P0）—— 仅对 qaxqjt_prod 库生效
--   qaxqjt_app  = 业务账号（读写无 DDL/DROP）
--   qaxqjt_read = 只读 BI 账号
-- ==============================================================================
GRANT SELECT, INSERT, UPDATE, DELETE
  ON ALL TABLES IN SCHEMA public TO qaxqjt_app;
GRANT SELECT, UPDATE
  ON ALL SEQUENCES IN SCHEMA public TO qaxqjt_app;
ALTER DEFAULT PRIVILEGES IN SCHEMA public
  GRANT SELECT, INSERT, UPDATE, DELETE ON TABLES TO qaxqjt_app;
ALTER DEFAULT PRIVILEGES IN SCHEMA public
  GRANT SELECT, UPDATE ON SEQUENCES TO qaxqjt_app;

GRANT SELECT ON ALL TABLES IN SCHEMA public TO qaxqjt_read;
ALTER DEFAULT PRIVILEGES IN SCHEMA public
  GRANT SELECT ON TABLES TO qaxqjt_read;

-- ==============================================================================
-- §2.3 种子初始化数据（PG 用 ON CONFLICT DO UPDATE = MySQL ON DUPLICATE KEY UPDATE）
-- ==============================================================================
-- 2.3.1 系统设置（与 MySQL 完全一致的 8 条）
INSERT INTO settings (id, key, value, "group", description, is_public, updated_by, _ts) VALUES
  ('set_troupe_name','troupeName','秦安县秦剧团文化演出有限公司','troupe','剧团全称（合同/发票/公开页显示）',TRUE,'sys_init',EXTRACT(EPOCH FROM now())::BIGINT*1000),
  ('set_troupe_phone','troupePhone','13993839833','troupe','对外联系电话',TRUE,'sys_init',EXTRACT(EPOCH FROM now())::BIGINT*1000),
  ('set_troupe_address','troupeAddress','甘肃省天水市秦安县陇城镇张沟村','troupe','注册地址',TRUE,'sys_init',EXTRACT(EPOCH FROM now())::BIGINT*1000),
  ('set_troupe_tax','troupeTaxNo','91620522MA1234567X（请替换为真实18位）','finance','开票抬头统一社会信用代码',FALSE,'sys_init',EXTRACT(EPOCH FROM now())::BIGINT*1000),
  ('set_troupe_legal','troupeLegalPerson','张维民','troupe','法人姓名',FALSE,'sys_init',EXTRACT(EPOCH FROM now())::BIGINT*1000),
  ('set_fin_double_above','financeDoubleCheckAbove','10000','finance','单笔凭证>=此金额强制双人复核(M-15)',FALSE,'sys_init',EXTRACT(EPOCH FROM now())::BIGINT*1000),
  ('set_booking_sms_verify','bookingSmsVerifyRequired','1','booking','公开预约是否强制短信验手机号(S-8)',FALSE,'sys_init',EXTRACT(EPOCH FROM now())::BIGINT*1000),
  ('set_booking_captcha','bookingCaptchaRequired','1','booking','公开预约是否强制行为验证码(M-10)',FALSE,'sys_init',EXTRACT(EPOCH FROM now())::BIGINT*1000)
ON CONFLICT (id) DO UPDATE SET
  value = EXCLUDED.value,
  updated_at = CURRENT_TIMESTAMP(0),
  updated_by = 'sys_init',
  _ts = EXTRACT(EPOCH FROM now())::BIGINT*1000;

-- 2.3.2 初始超级管理员（M-14 force_pwd_change=TRUE，password_hash占位必换！）
INSERT INTO accounts_v2
  (id, username, password_hash, real_name, role, phone, email, status, force_pwd_change, created_by, _ts)
VALUES
  ('acc_superadmin_001', 'admin',
   '$2b$12$EixZaYVK1fsbw1ZfbX3OXePaWxn96p36WQoeG6Lruj3vjPGga31lW' /* 占位必换！ */,
   '超级管理员-24小时内强制修改密码', 'super_admin', '13993839833',
   'admin@qaxqjt.cn', 'active', TRUE, 'sys_init', EXTRACT(EPOCH FROM now())::BIGINT*1000)
ON CONFLICT (id) DO UPDATE SET
  updated_at = CURRENT_TIMESTAMP(0),
  force_pwd_change = TRUE;

-- 2.3.3 9 角色（4 基础 + 5 扩展，M-15 财务 3 角色拆分）
INSERT INTO roles (id, name, description, level, created_by, _ts) VALUES
  ('role_super','超级管理员','全权限（团长+CTO，<3人）',999,'sys_init',EXTRACT(EPOCH FROM now())::BIGINT*1000),
  ('role_ops','运营调度','预约/订单/档期/演员表/考勤 可写',800,'sys_init',EXTRACT(EPOCH FROM now())::BIGINT*1000),
  ('role_director','团长/业务副团长','全局只读 + 订单审批/档期锁',700,'sys_init',EXTRACT(EPOCH FROM now())::BIGINT*1000),
  ('role_finance_admin','财务主管','全财务权限 + 月度关账',500,'sys_init',EXTRACT(EPOCH FROM now())::BIGINT*1000),
  ('role_finance_checker','财务复核岗','复核制单/关账/对账 只可写不可制单',600,'sys_init',EXTRACT(EPOCH FROM now())::BIGINT*1000),
  ('role_finance_maker','财务制单岗','只能制单，不能复核本人凭证（M-15双角色）',550,'sys_init',EXTRACT(EPOCH FROM now())::BIGINT*1000),
  ('role_finance_cashier','出纳岗','收付款/银行回单上传，无记账权限',520,'sys_init',EXTRACT(EPOCH FROM now())::BIGINT*1000),
  ('role_finance_view','财务只读','只读财务报表/凭证',510,'sys_init',EXTRACT(EPOCH FROM now())::BIGINT*1000),
  ('role_staff','普通员工','个人考勤/工资条/请假提交 只读',100,'sys_init',EXTRACT(EPOCH FROM now())::BIGINT*1000)
ON CONFLICT (id) DO UPDATE SET
  updated_at = CURRENT_TIMESTAMP(0), updated_by = 'sys_init';

-- 2.3.4 4 级工资等级（A+/A/B/C）
INSERT INTO wage_rules_v1
  (id, rank_grade, base_daily_standard, chief_role_allowance, supporting_role_base,
   ensemble_base, crew_band_base, tech_dancer_base, night_show_bonus,
   holiday_multiplier, transport_allowance, meal_allowance, full_attendance_bonus,
   performance_bonus_rate, effective_from_date, created_by, _ts)
VALUES
  ('wrule_ap','A+',1800,800,400,300,400,500,200,2.0000,60,60,500,0.0800,'2026-01-01','sys_init',EXTRACT(EPOCH FROM now())::BIGINT*1000),
  ('wrule_a', 'A', 1200,500,250,180,250,300,150,1.5000,40,50,300,0.0600,'2026-01-01','sys_init',EXTRACT(EPOCH FROM now())::BIGINT*1000),
  ('wrule_b', 'B',  800,300,150,120,180,220,100,1.3000,30,40,200,0.0500,'2026-01-01','sys_init',EXTRACT(EPOCH FROM now())::BIGINT*1000),
  ('wrule_c', 'C',  500,150,80, 60, 120,160, 60,1.1000,30,30,100,0.0300,'2026-01-01','sys_init',EXTRACT(EPOCH FROM now())::BIGINT*1000)
ON CONFLICT (id) DO UPDATE SET
  updated_at = CURRENT_TIMESTAMP(0), _ts = EXTRACT(EPOCH FROM now())::BIGINT*1000;

-- 2.3.5 迁移标记
INSERT INTO data_migrations
  (id, batch, description, executed_by, expected_row_count, actual_row_count, dry_run, status, _ts)
VALUES
  ('v1.0_initial', 1, 'PG 13+ 42表DDL+15索引+种子数据初始化',
   'sql_script @ docker-entrypoint-initdb.d', 42, 42, FALSE, 'success', EXTRACT(EPOCH FROM now())::BIGINT*1000)
ON CONFLICT (id) DO UPDATE SET status='success';

-- ==============================================================================
-- 方案 B · 覆盖重建（PG 版）参考：
--   DROP TABLE IF EXISTS overtime_records,leave_applications,attendance_punch_records,attendance_v1 CASCADE;
--   DROP TABLE IF EXISTS fin_debts_v1,fin_recons_v1,fin_invoices_v1,fin_ledger_v1,wage_items_v1,wage_batches_v1,wage_rules_v1 CASCADE;
--   DROP TABLE IF EXISTS cast_sheet_crew,cast_sheets_v1,schedule_venues,schedules_v2,order_refunds,fin_payments_v1,order_items,orders CASCADE;
--   DROP TABLE IF EXISTS appointment_audit,appointment_plays,appointments,customer_tags,customer_contacts,customers_v1 CASCADE;
--   DROP TABLE IF EXISTS content_v2,inventory_records,inventory_items,play_casts,plays,performers_db_v1 CASCADE;
--   DROP TABLE IF EXISTS data_migrations,system_backups,settings,login_attempts,audit_logs,admin_sessions,user_roles,role_permissions,permissions,roles,accounts_v2 CASCADE;
--   再从第 1 行开始重新执行本脚本 = 完全干净空库 + 种子数据
-- ==============================================================================
--  Script End · PostgreSQL 13+ · 42 tables · 7 batches · 15+ indexes · ENUM via CHECK+VARCHAR
--  · ON CONFLICT 幂等种子 · tg_set_updated_at 触发器 · pgcrypto/pg_trgm 扩展启用
